[[GAP_pkg_ace]]
arch = "aarch64"
git-tree-sha1 = "6445900991ea5d64aa846e3194826ad8d700df49"
os = "macos"

    [[GAP_pkg_ace.download]]
    sha256 = "9480aec556eea9c17996ffde0de4c7da9a1d9e6c2aec58be988a2f3fc895f97d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_ace]]
arch = "aarch64"
git-tree-sha1 = "fda74cb6245e8dde7070d58de993b2d5a298376e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ace.download]]
    sha256 = "f231e9b62b7feab459853fa91402734800c96f2a376d30997c95c520885e5767"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_ace]]
arch = "aarch64"
git-tree-sha1 = "a0263221630d6a1a8248ec56663d2ac886ee2520"
libc = "musl"
os = "linux"

    [[GAP_pkg_ace.download]]
    sha256 = "d6d6a657da73c7d022e41392c4c189b7e605db3d3f541628c334c06de79a5a75"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_ace]]
arch = "powerpc64le"
git-tree-sha1 = "37e07b6f5602f7dfe5f9d4a82427351d88cd6ef9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ace.download]]
    sha256 = "e104c5681c94db5e62c287ae332a885f6ddfbc087752f7e5ca23290a6f67793c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_ace]]
arch = "x86_64"
git-tree-sha1 = "d20e6c09ad1c85bc34195f57fe27476236ab97e8"
os = "macos"

    [[GAP_pkg_ace.download]]
    sha256 = "8a4a9def1b69e8750a7d3eb2cfd1efad5bcf7d01dd5b3d9683bd42e0fcb823cd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ace]]
arch = "x86_64"
git-tree-sha1 = "098709c4f974aac0eb040a9cc0c4a11a17c0a05a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ace.download]]
    sha256 = "69f06ba608d96ef132d904024e3e5edf38d04964cb4a8ee462476e5a1e0bc2c9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_ace]]
arch = "x86_64"
git-tree-sha1 = "6079518e2221b945af93a6f4f5b1a12d8c813521"
libc = "musl"
os = "linux"

    [[GAP_pkg_ace.download]]
    sha256 = "275357b46c82ed66dd5241f6ba62280baf39bebcad4244eb6181b7502aa0cc7f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_ace]]
arch = "x86_64"
git-tree-sha1 = "b9fcacd7c57c76dc0f003ddc1b5bd3e6e7dbd61c"
os = "freebsd"

    [[GAP_pkg_ace.download]]
    sha256 = "433770f2dcc3d008d92441510fea427dff314d4a2a7925babf77f3822e37ddfe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ace_jll.jl/releases/download/GAP_pkg_ace-v500.600.200+0/GAP_pkg_ace.v500.600.200.x86_64-unknown-freebsd.tar.gz"
